### ISSUE TITLE
Typo Correction

### ISSUE THREAD

**Issue by muriithi-ma** [pdfshift/www.pdfshift.io#27]
Hi?

I was browsing through your website and came across some typo under the pricing__contact div. It reads "Dontact Us". I believe it should read "Contact Us". 

Below is a photo reference.

![2023-06-30 14_40_37-Fast, Easy Website and HTML to PDF Converter via API _ PDFShift](https://github.com/pdfshift/www.pdfshift.io/assets/107982870/f6987f9b-f22f-4fd2-afc7-42b0c24fe3ab)

**Comment by cnicodeme** [comment]
Oh right! that's a shame ... :D
Thank you for catching it! It's resolved now.

**Comment by muriithi-ma** [comment]
Great ... Good as new now ... :D
